#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$ROOT_DIR/getout.sh"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

modules=(
  src/00_prelude.sh
  src/01_constants.sh
  src/02_logging.sh
  src/03_update.sh
  src/04_config.sh
  src/06_rollback.sh
  src/07_deps_downloads.sh
  src/08_helpers.sh
  src/09_runtime_safety.sh
  src/10_route_scripts.sh
  src/11_server.sh
  src/12_client.sh
  src/13_lifecycle_status_doctor.sh
  src/14_cli.sh
)

fail() { echo "build.sh: $*" >&2; exit 1; }

validate_modules() {
  local module path src_file rel seen_key
  declare -A seen=()

  [ -d "$ROOT_DIR/src" ] || fail "missing src directory"

  for module in "${modules[@]}"; do
    [[ "$module" == src/*.sh ]] || fail "module must be under src/*.sh: $module"
    path="$ROOT_DIR/$module"
    [ -f "$path" ] || fail "missing module: $module"
    seen_key="$module"
    [ -z "${seen[$seen_key]:-}" ] || fail "duplicate module in build order: $module"
    seen[$seen_key]=1
  done

  while IFS= read -r src_file; do
    rel="${src_file#$ROOT_DIR/}"
    [ -n "${seen[$rel]:-}" ] || fail "src module is not listed in build order: $rel"
  done < <(find "$ROOT_DIR/src" -maxdepth 1 -type f -name '*.sh' | sort)
}

validate_modules
: > "$TMP"
for module in "${modules[@]}"; do
  cat "$ROOT_DIR/$module" >> "$TMP"
  if [ "$module" = "src/00_prelude.sh" ]; then
    cat >> "$TMP" <<'EOF_NOTICE'
# Generated by build.sh from src/*.sh. Do not edit getout.sh directly.
# Edit src/*.sh, then run ./build.sh.

EOF_NOTICE
  fi
done

bash -n "$TMP"
install -m 0755 "$TMP" "$OUT"
(
  cd "$ROOT_DIR"
  sha256sum "$(basename "$OUT")" > "$(basename "$OUT").sha256"
)
