#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$ROOT_DIR/getout.sh"
TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

pass() { printf '[OK] %s\n' "$*"; }

make_lib() {
  local lib="$1"
  awk '/^main "\$@"/ {exit} {print}' "$SCRIPT" > "$lib"
}

run_build_output_is_current() {
  local before_script="$TMP_ROOT/getout.before" before_hash="$TMP_ROOT/getout.sha256.before"
  cp "$ROOT_DIR/getout.sh" "$before_script"
  cp "$ROOT_DIR/getout.sh.sha256" "$before_hash"
  "$ROOT_DIR/build.sh" >/dev/null
  cmp -s "$before_script" "$ROOT_DIR/getout.sh"
  cmp -s "$before_hash" "$ROOT_DIR/getout.sh.sha256"
  grep -q 'Generated by build.sh from src/\*.sh' "$ROOT_DIR/getout.sh"
  pass 'build.sh output is current and marked generated'
}

run_bash_syntax() {
  bash -n "$SCRIPT"
  pass 'getout.sh syntax'
}

run_route_script_syntax() {
  local t="$TMP_ROOT/routes"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    CLIENT_CONF="$CONF_DIR/client.conf"
    ROUTES_UP="$CONF_DIR/routes-up.sh"
    ROUTES_DOWN="$CONF_DIR/routes-down.sh"
    mkdir -p "$CONF_DIR"
    write_routes_scripts
    bash -n "$ROUTES_UP"
    bash -n "$ROUTES_DOWN"
    grep -q '^ensure_nftables()' "$ROUTES_UP"
    ! grep -q 'apt-get' "$ROUTES_UP"
  )
  pass 'generated route scripts syntax'
}

run_runtime_restore_deletes_new_files() {
  local t="$TMP_ROOT/runtime"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/etc-getout"
    CLIENT_CONF="$CONF_DIR/client.conf"
    TUN_CONF="$CONF_DIR/tun2socks.yaml"
    WG_CONF="$CONF_DIR/getout-wg0.conf"
    ROUTES_UP="$CONF_DIR/routes-up.sh"
    ROUTES_DOWN="$CONF_DIR/routes-down.sh"
    TUN_SERVICE="$t/getout-tun.service"
    WG_SERVICE="$t/getout-wg.service"
    MODE_FILE="$CONF_DIR/mode"
    systemctl() { :; }
    mkdir -p "$CONF_DIR"
    printf 'old-client\n' > "$CLIENT_CONF"
    printf 'old-routes-up\n' > "$ROUTES_UP"
    printf 'old-wg-conf\n' > "$WG_CONF"
    printf 'old-wg-service\n' > "$WG_SERVICE"
    snapshot="$(snapshot_runtime_files)"
    begin_runtime_rollback "$snapshot"
    printf 'new-client\n' > "$CLIENT_CONF"
    printf 'new-tun\n' > "$TUN_CONF"
    printf 'new-routes-up\n' > "$ROUTES_UP"
    printf 'new-routes-down\n' > "$ROUTES_DOWN"
    printf 'new-service\n' > "$TUN_SERVICE"
    printf 'new-wg-conf\n' > "$WG_CONF"
    printf 'new-wg-service\n' > "$WG_SERVICE"
    printf 'dual\n' > "$MODE_FILE"
    restore_runtime_or_warn "$snapshot" >/dev/null 2>&1
    [ "$(cat "$CLIENT_CONF")" = old-client ]
    [ "$(cat "$ROUTES_UP")" = old-routes-up ]
    [ "$(cat "$WG_CONF")" = old-wg-conf ]
    [ "$(cat "$WG_SERVICE")" = old-wg-service ]
    [ ! -e "$TUN_CONF" ]
    [ ! -e "$ROUTES_DOWN" ]
    [ ! -e "$TUN_SERVICE" ]
    [ ! -e "$MODE_FILE" ]
  )
  pass 'runtime rollback restores old files and deletes new files'
}

run_preflight_failure_rolls_back() {
  local t="$TMP_ROOT/preflight"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  cat > "$t/case.sh" <<'CASE'
#!/usr/bin/env bash
set -euo pipefail
. "$1"
root="$2"
CONF_DIR="$root/etc-getout"
CLIENT_CONF="$CONF_DIR/client.conf"
TUN_CONF="$CONF_DIR/tun2socks.yaml"
ROUTES_UP="$CONF_DIR/routes-up.sh"
ROUTES_DOWN="$CONF_DIR/routes-down.sh"
TUN_SERVICE="$root/getout-tun.service"
MODE_FILE="$CONF_DIR/mode"
TUN_BIN="$root/missing-tun2socks"
systemctl() { :; }
mkdir -p "$CONF_DIR"
printf 'old-client\n' > "$CLIENT_CONF"
snapshot="$(snapshot_runtime_files)"
begin_runtime_rollback "$snapshot"
printf '%s\n' "$snapshot" > "$root/snapshot-path"
printf 'new-client\n' > "$CLIENT_CONF"
printf 'new-tun\n' > "$TUN_CONF"
preflight_tun_runtime_with_rollback "$snapshot"
CASE
  set +e
  out="$(bash "$t/case.sh" "$lib" "$t/root" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -eq 1 ]
  [ "$(cat "$t/root/etc-getout/client.conf")" = old-client ]
  [ ! -e "$t/root/etc-getout/tun2socks.yaml" ]
  snapshot="$(cat "$t/root/snapshot-path")"
  [ ! -d "$snapshot" ]
  grep -q '未找到可执行 tun2socks' <<<"$out"
  pass 'preflight failure rolls back runtime snapshot'
}

run_daemon_reload_failure_rolls_back_runtime() {
  local t="$TMP_ROOT/daemon"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  cat > "$t/case.sh" <<'CASE'
#!/usr/bin/env bash
set -euo pipefail
. "$1"
root="$2"
CONF_DIR="$root/etc-getout"
CLIENT_CONF="$CONF_DIR/client.conf"
TUN_CONF="$CONF_DIR/tun2socks.yaml"
ROUTES_UP="$CONF_DIR/routes-up.sh"
ROUTES_DOWN="$CONF_DIR/routes-down.sh"
TUN_SERVICE="$root/getout-tun.service"
MODE_FILE="$CONF_DIR/mode"
TUN_BIN="$root/getout-tun2socks"
systemctl() { return 1; }
mkdir -p "$CONF_DIR"
printf 'old-client\n' > "$CLIENT_CONF"
printf 'old-service\n' > "$TUN_SERVICE"
snapshot="$(snapshot_runtime_files)"
begin_runtime_rollback "$snapshot"
printf '%s\n' "$snapshot" > "$root/snapshot-path"
cat > "$CLIENT_CONF" <<CONF
MODE=v4
SOCKS_ADDRESS=127.0.0.1
SOCKS_PORT=1080
SOCKS_USERNAME=
SOCKS_PASSWORD=
TABLE_ID=20
MARK_ID=438
BYPASS_MARK_ID=439
NFT_TABLE=getout_protect
TUN_NAME=tun0
CONF
write_tun_service v4
clear_runtime_rollback "$snapshot"
CASE
  set +e
  out="$(bash "$t/case.sh" "$lib" "$t/root" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -eq 1 ]
  [ "$(cat "$t/root/etc-getout/client.conf")" = old-client ]
  [ "$(cat "$t/root/getout-tun.service")" = old-service ]
  snapshot="$(cat "$t/root/snapshot-path")"
  [ ! -d "$snapshot" ]
  grep -q '已尝试恢复旧配置和旧 systemd 文件' <<<"$out"
  pass 'daemon-reload failure rolls back runtime snapshot'
}

run_server_daemon_reload_failure_rolls_back() {
  local t="$TMP_ROOT/server"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  cat > "$t/case.sh" <<'CASE'
#!/usr/bin/env bash
set -euo pipefail
. "$1"
root="$2"
CONF_DIR="$root/etc-getout"
SERVER_CONF="$CONF_DIR/server.conf"
GOST_SERVICE="$root/getout-gost.service"
MODE_FILE="$CONF_DIR/mode"
systemctl() { return 1; }
mkdir -p "$CONF_DIR"
printf 'old-server\n' > "$SERVER_CONF"
printf 'old-service\n' > "$GOST_SERVICE"
snapshot="$(snapshot_server_files)"
begin_server_rollback "$snapshot"
printf '%s\n' "$snapshot" > "$root/snapshot-path"
cat > "$SERVER_CONF" <<CONF
PORT=1080
USERNAME=user
PASSWORD=pass
CONF
write_gost_service
clear_runtime_rollback "$snapshot"
CASE
  set +e
  out="$(bash "$t/case.sh" "$lib" "$t/root" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -eq 1 ]
  [ "$(cat "$t/root/etc-getout/server.conf")" = old-server ]
  [ "$(cat "$t/root/getout-gost.service")" = old-service ]
  snapshot="$(cat "$t/root/snapshot-path")"
  [ ! -d "$snapshot" ]
  grep -q '入口启动失败，已尝试恢复旧入口配置和旧 systemd 文件' <<<"$out"
  pass 'entry daemon-reload failure rolls back server snapshot'
}

run_stop_cleanup_order_protects_control_plane() {
  local t="$TMP_ROOT/stop-order"
  local lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    CLIENT_CONF="$CONF_DIR/client.conf"
    TUN_CONF="$CONF_DIR/tun2socks.yaml"
    ROUTES_UP="$CONF_DIR/routes-up.sh"
    ROUTES_DOWN="$CONF_DIR/routes-down.sh"
    TUN_SERVICE="$t/getout-tun.service"
    TUN_BIN="$t/getout-tun2socks"
    systemctl() { :; }
    mkdir -p "$CONF_DIR"
    write_routes_scripts
    write_tun_service dual
    lookup_line="$(grep -n 'ip rule del lookup "\$TABLE_ID" pref 20' "$ROUTES_DOWN" | head -n1 | cut -d: -f1)"
    nft_line="$(grep -n 'nft delete table inet "\$NFT_TABLE"' "$ROUTES_DOWN" | head -n1 | cut -d: -f1)"
    [ -n "$lookup_line" ] && [ -n "$nft_line" ] && [ "$lookup_line" -lt "$nft_line" ]
    grep -q "^ExecStop=$ROUTES_DOWN$" "$TUN_SERVICE"
    grep -q "^ExecStopPost=$ROUTES_DOWN$" "$TUN_SERVICE"
  )
  pass 'stop cleanup removes global tun route before protection rules'
}

run_password_prompts_are_plaintext() {
  ! grep -Eq 'read[[:space:]][^\n]*-[^\n]*s' "$SCRIPT"
  grep -q '上游 SOCKS5 用户名 \[无认证可留空\]' "$SCRIPT"
  grep -q '上游 SOCKS5 密码 \[无认证可留空\]' "$SCRIPT"
  pass 'password prompts use plaintext input and outlet auth remains optional'
}

run_menu_order_matches_readme() {
  local status_line restart_line update_line uninstall_line exit_line
  status_line="$(grep -n '查看状态' "$SCRIPT" | grep 'echo' | head -n1 | cut -d: -f1)"
  restart_line="$(grep -n '重启 getout' "$SCRIPT" | grep 'echo' | head -n1 | cut -d: -f1)"
  update_line="$(grep -n '更新 getout' "$SCRIPT" | grep 'echo' | head -n1 | cut -d: -f1)"
  uninstall_line="$(grep -n '卸载 getout' "$SCRIPT" | grep 'echo' | head -n1 | cut -d: -f1)"
  exit_line="$(grep -n '退出' "$SCRIPT" | grep 'echo' | grep -v '已取消' | head -n1 | cut -d: -f1)"
  [ -n "$status_line" ] && [ -n "$restart_line" ] && [ -n "$update_line" ] && [ -n "$uninstall_line" ] && [ -n "$exit_line" ]
  [ "$status_line" -lt "$restart_line" ] && [ "$restart_line" -lt "$update_line" ] && [ "$update_line" -lt "$uninstall_line" ] && [ "$uninstall_line" -lt "$exit_line" ]
  grep -q '请选择 \[1-' "$SCRIPT"
  grep -q '请选择 \[1/2\]' "$SCRIPT"
  grep -q 'echo "  1\. SOCKS5 模式"' "$SCRIPT"
  grep -q 'echo "  2\. WireGuard 模式"' "$SCRIPT"
  ! grep -q '请选择 \[a/b\]' "$SCRIPT"
  ! grep -q 'echo "9\.环境诊断"' "$SCRIPT"
  pass 'menu order matches documented release menu'
}

run_checksum_file_matches_script() {
  [ -f "$ROOT_DIR/getout.sh.sha256" ]
  (cd "$ROOT_DIR" && sha256sum -c getout.sh.sha256 >/dev/null)
  pass 'repository getout.sh.sha256 matches getout.sh'
}

run_checksum_verification() {
  local t="$TMP_ROOT/checksum"
  local lib="$t/lib.sh" sample="$t/sample.sh"
  mkdir -p "$t"
  make_lib "$lib"
  printf 'hello\n' > "$sample"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    GETOUT_UPDATE_SHA256="$(sha256sum "$sample" | awk '{print $1}')"
    verify_update_checksum "$sample"
  )
  set +e
  out="$(bash -c '. "$1"; GETOUT_UPDATE_SHA256=bad verify_update_checksum "$2"' _ "$lib" "$sample" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -ne 0 ]
  grep -q 'SHA256 校验失败' <<<"$out"
  pass 'update checksum verification accepts match and rejects mismatch'
}


run_update_warns_when_wg_service_active() {
  local t="$TMP_ROOT/update-wg" lib out
  lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  out="$(bash -c '
    set -euo pipefail
    . "$1"
    require_root() { :; }
    install_from_update_url() { :; }
    service_active() { [ "$1" = getout-wg.service ]; }
    update_getout
  ' _ "$lib" 2>&1)"
  grep -q 'getout 正在运行' <<<"$out"
  pass 'update warns when WireGuard service is active'
}

run_binary_checksum_verification() {
  local t="$TMP_ROOT/binary-checksum"
  local lib="$t/lib.sh" sample="$t/sample.bin"
  mkdir -p "$t"
  make_lib "$lib"
  printf 'binary\n' > "$sample"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    verify_download_sha256 "$sample" "$(sha256sum "$sample" | awk '{print $1}')" "sample binary"
    [ -n "${GOST_SHA256[amd64]:-}" ]
    [ -n "${GOST_SHA256[armv8]:-}" ]
    [ -n "${HEV_SHA256[x86_64]:-}" ]
    [ -n "${HEV_SHA256[arm64]:-}" ]
  )
  set +e
  out="$(bash -c '. "$1"; verify_download_sha256 "$2" bad "sample binary"' _ "$lib" "$sample" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -ne 0 ]
  grep -q 'sample binary SHA256 校验失败' <<<"$out"
  pass 'third-party binary checksum verification accepts match and rejects mismatch'
}

run_restart_service_with_rollback_restores_on_failure() {
  local t="$TMP_ROOT/restart-rollback" lib out rc
  lib="$t/lib.sh"
  mkdir -p "$t"
  make_lib "$lib"
  cat > "$t/case.sh" <<'CASE'
#!/usr/bin/env bash
set -euo pipefail
. "$1"
root="$2"
snapshot="$root/snapshot"
mkdir -p "$snapshot"
systemctl() {
  case "$1" in
    restart) return 0 ;;
    is-active) return 1 ;;
  esac
}
restore_test() { echo restored > "$root/restored"; }
restart_service_with_rollback getout-test.service "$snapshot" restore_test restart 0 boom
CASE
  set +e
  out="$(bash "$t/case.sh" "$lib" "$t" 2>&1)"
  rc=$?
  set -e
  [ "$rc" -eq 1 ]
  [ "$(cat "$t/restored")" = restored ]
  grep -q 'boom' <<<"$out"
  pass 'service restart rollback helper restores on failure'
}

run_client_config_writes_common_runtime_fields() {
  local t="$TMP_ROOT/client-conf" lib
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    CLIENT_CONF="$CONF_DIR/client.conf"
    ssh_remote_ip() { echo 198.51.100.2; }
    ssh_listen_ports() { echo 22; }
    main_ipv4() { echo 203.0.113.1; }
    main_ipv6() { echo 2001:db8::1; }
    write_client_conf v4 socks.example 1080 user pass v4
    grep -q '^SSH_REMOTE_IP=198.51.100.2$' "$CLIENT_CONF"
    grep -q '^TUN_NAME=tun0$' "$CLIENT_CONF"
    grep -q '^PRIORITY_MODE=v4$' "$CLIENT_CONF"
    write_wg_client_conf wg-dual wg.example 62233 client-key '10.66.66.2/32, fd86:ea04:1115::2/128' server-pub '' '' v6
    grep -q '^SSH_REMOTE_IP=198.51.100.2$' "$CLIENT_CONF"
    grep -q '^IFACE=getout-wg0$' "$CLIENT_CONF"
    grep -q '^TUN_NAME=getout-wg0$' "$CLIENT_CONF"
    grep -q '^PRIORITY_MODE=v6$' "$CLIENT_CONF"
  )
  pass 'client configs share common runtime fields'
}

run_wg_server_status_prints_peer_credentials() {
  local t="$TMP_ROOT/wg-status" lib out
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  cat > "$t/conf/server.conf" <<'CONF'
SERVER_MODE=wireguard
LISTEN_PORT=62233
PRIVATE_KEY=server-private
PEER_PRIVATE_KEY=client-private
PEER_PUBLIC_KEY=client-public
CONF
  chmod 600 "$t/conf/server.conf"
  out="$( (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    SERVER_CONF="$CONF_DIR/server.conf"
    CLIENT_CONF="$CONF_DIR/client.conf"
    MODE_FILE="$CONF_DIR/mode"
    SCRIPT_VERSION=test
    CYAN= NC=
    current_mode() { echo wg-server; }
    server_active() { return 1; }
    tun_active() { return 1; }
    wg_server_active() { return 1; }
    wg_client_active() { return 1; }
    service_enabled_text() { echo disabled; }
    main_ipv4() { echo 203.0.113.1; }
    main_ipv6() { return 1; }
    wg() { cat >/dev/null; echo server-public; }
    curl() { echo test-ip; }
    status
  ) 2>&1)"
  grep -q '地址: 203.0.113.1' <<<"$out"
  grep -q '私钥: client-private' <<<"$out"
  grep -q '公钥: server-public' <<<"$out"
  ! grep -q '私钥: server-private' <<<"$out"
  pass 'WireGuard entry status prints peer private key and server public key'
}



run_wg_units_use_explicit_shell_for_cleanup() {
  local t="$TMP_ROOT/wg-unit-shell" lib
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    WG_CONF="$CONF_DIR/getout-wg0.conf"
    WG_SERVICE="$t/getout-wg.service"
    ROUTES_UP="$t/routes-up.sh"
    ROUTES_DOWN="$t/routes-down.sh"
    systemctl() { :; }
    write_wg_service wg-v4
    grep -q '^ExecStopPost=/bin/sh -c' "$WG_SERVICE"
    ! grep -q '^ExecStopPost=/usr/bin/wg-quick.*2>/dev/null || true' "$WG_SERVICE"
    write_wg_systemd_service 'Getout WireGuard Server'
    grep -q '^ExecStopPost=/bin/sh -c' "$WG_SERVICE"
    ! grep -q '^ExecStopPost=/usr/bin/wg-quick.*2>/dev/null || true' "$WG_SERVICE"
  )
  pass 'WireGuard units use explicit shell for cleanup fallback'
}

run_wg_config_rejects_injected_values() {
  local t="$TMP_ROOT/wg-injection" lib out rc
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  cat > "$t/conf/client.conf" <<'CONF'
MODE=wg-v4
TRANSPORT=wireguard
WG_SERVER_ADDRESS=example.com
WG_SERVER_PORT=62233
WG_CLIENT_PRIVATE_KEY='bad
PostUp = touch /tmp/pwned'
WG_CLIENT_ADDRESS=10.66.66.2/32
WG_SERVER_PUBLIC_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
WG_PRESHARED_KEY=
WG_DNS=
CONF
  chmod 600 "$t/conf/client.conf"
  set +e
  out="$( (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    CLIENT_CONF="$CONF_DIR/client.conf"
    WG_CONF="$t/wg.conf"
    write_wg_config
  ) 2>&1)"
  rc=$?
  set -e
  [ "$rc" -ne 0 ]
  grep -q 'WG_CLIENT_PRIVATE_KEY 无效' <<<"$out"
  [ ! -f "$t/wg.conf" ]
  pass 'WireGuard client config rejects newline injection before writing wg config'
}

run_wg_server_rejects_injected_values() {
  local t="$TMP_ROOT/wg-server-injection" lib out rc
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  cat > "$t/conf/server.conf" <<'CONF'
SERVER_MODE=wireguard
LISTEN_PORT=62233
PRIVATE_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
ADDRESS='10.66.66.1/30
PostUp = touch /tmp/pwned'
PEER_PUBLIC_KEY=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb=
ALLOWED_IPS=10.66.66.2/32
CONF
  chmod 600 "$t/conf/server.conf"
  set +e
  out="$( (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    SERVER_CONF="$CONF_DIR/server.conf"
    WG_CONF="$t/wg.conf"
    WG_SERVICE="$t/wg.service"
    systemctl() { :; }
    write_wg_server_service
  ) 2>&1)"
  rc=$?
  set -e
  [ "$rc" -ne 0 ]
  grep -q 'ADDRESS 无效' <<<"$out"
  [ ! -f "$t/wg.conf" ]
  pass 'WireGuard server config rejects newline injection before writing wg config'
}


run_wg_server_mode_is_not_client_mode() {
  local t="$TMP_ROOT/wg-mode" lib
  lib="$t/lib.sh"
  mkdir -p "$t/conf"
  make_lib "$lib"
  (
    set -euo pipefail
    # shellcheck disable=SC1090
    . "$lib"
    CONF_DIR="$t/conf"
    MODE_FILE="$CONF_DIR/mode"
    mkdir -p "$CONF_DIR"
    echo wg-server > "$MODE_FILE"
    systemctl() { [ "$1" = is-active ] && [ "${3:-}" = getout-wg.service ]; }
    wg_server_active
    ! wg_client_active
    ! client_mode_active wg-server
  )
  pass 'wg-server mode is not treated as a WireGuard client mode'
}

run_build_output_is_current
run_bash_syntax
run_route_script_syntax
run_runtime_restore_deletes_new_files
run_preflight_failure_rolls_back
run_daemon_reload_failure_rolls_back_runtime
run_server_daemon_reload_failure_rolls_back
run_stop_cleanup_order_protects_control_plane
run_password_prompts_are_plaintext
run_menu_order_matches_readme
run_checksum_file_matches_script
run_checksum_verification
run_update_warns_when_wg_service_active
run_binary_checksum_verification
run_restart_service_with_rollback_restores_on_failure
run_client_config_writes_common_runtime_fields
run_wg_server_status_prints_peer_credentials
run_wg_server_mode_is_not_client_mode
run_wg_units_use_explicit_shell_for_cleanup
run_wg_config_rejects_injected_values
run_wg_server_rejects_injected_values
